// Core의 UpgradeType과 동기화된 enum
export enum UpgradeType {
  Terran_Infantry_Armor = 0,
  Terran_Vehicle_Plating = 1,
  Terran_Ship_Plating = 2,
  Zerg_Carapace = 3,
  Zerg_Flyer_Carapace = 4,
  Protoss_Ground_Armor = 5,
  Protoss_Air_Armor = 6,
  Terran_Infantry_Weapons = 7,
  Terran_Vehicle_Weapons = 8,
  Terran_Ship_Weapons = 9,
  Zerg_Melee_Attacks = 10,
  Zerg_Missile_Attacks = 11,
  Zerg_Flyer_Attacks = 12,
  Protoss_Ground_Weapons = 13,
  Protoss_Air_Weapons = 14,
  Protoss_Plasma_Shields = 15,
  U_238_Shells = 16,
  Ion_Thrusters = 17,
  Titan_Reactor = 19,
  Ocular_Implants = 20,
  Moebius_Reactor = 21,
  Apollo_Reactor = 22,
  Colossus_Reactor = 23,
  Ventral_Sacs = 24,
  Antennae = 25,
  Pneumatized_Carapace = 26,
  Metabolic_Boost = 27,
  Adrenal_Glands = 28,
  Muscular_Augments = 29,
  Grooved_Spines = 30,
  Gamete_Meiosis = 31,
  Metasynaptic_Node = 32,
  Singularity_Charge = 33,
  Leg_Enhancements = 34,
  Scarab_Damage = 35,
  Reaver_Capacity = 36,
  Gravitic_Drive = 37,
  Sensor_Array = 38,
  Gravitic_Boosters = 39,
  Khaydarin_Amulet = 40,
  Apial_Sensors = 41,
  Gravitic_Thrusters = 42,
  Carrier_Capacity = 43,
  Khaydarin_Core = 44,
  Argus_Jewel = 47,
  Argus_Talisman = 49,
  Caduceus_Reactor = 51,
  Chitinous_Plating = 52,
  Anabolic_Synthesis = 53,
  Charon_Boosters = 54,
  Upgrade_60 = 60,
  None = 61,
  Unknown = 62,
  MAX = 63
}

// 업그레이드 이름 매핑 (한국어)
export const UPGRADE_NAMES = {
  // Terran Upgrades
  [UpgradeType.Terran_Infantry_Armor]: '보병 방어력',
  [UpgradeType.Terran_Vehicle_Plating]: '차량 방어력',
  [UpgradeType.Terran_Ship_Plating]: '우주선 방어력',
  [UpgradeType.Terran_Infantry_Weapons]: '보병 공격력',
  [UpgradeType.Terran_Vehicle_Weapons]: '차량 공격력',
  [UpgradeType.Terran_Ship_Weapons]: '우주선 공격력',
  [UpgradeType.U_238_Shells]: 'U-238 쉘',
  [UpgradeType.Ion_Thrusters]: '이온 스러스터',
  [UpgradeType.Titan_Reactor]: '타이탄 리액터',
  [UpgradeType.Ocular_Implants]: '오큘러 임플란츠',
  [UpgradeType.Moebius_Reactor]: '뫼비우스 리액터',
  [UpgradeType.Apollo_Reactor]: '아폴로 리액터',
  [UpgradeType.Colossus_Reactor]: '콜로서스 리액터',
  [UpgradeType.Caduceus_Reactor]: '카두세우스 리액터',
  [UpgradeType.Charon_Boosters]: '카론 부스터',
  
  // Zerg Upgrades
  [UpgradeType.Zerg_Carapace]: '갑피',
  [UpgradeType.Zerg_Flyer_Carapace]: '비행체 갑피',
  [UpgradeType.Zerg_Melee_Attacks]: '근접 공격',
  [UpgradeType.Zerg_Missile_Attacks]: '미사일 공격',
  [UpgradeType.Zerg_Flyer_Attacks]: '비행체 공격',
  [UpgradeType.Ventral_Sacs]: '벤트럴 섹',
  [UpgradeType.Antennae]: '안테나',
  [UpgradeType.Pneumatized_Carapace]: '뉴머타이즈드 캐러페이스',
  [UpgradeType.Metabolic_Boost]: '메타볼릭 부스트',
  [UpgradeType.Adrenal_Glands]: '아드레날 글랜즈',
  [UpgradeType.Muscular_Augments]: '머스큘러 아규먼츠',
  [UpgradeType.Grooved_Spines]: '그루브드 스파인스',
  [UpgradeType.Gamete_Meiosis]: '게미트 마이오시스',
  [UpgradeType.Metasynaptic_Node]: '메타시냅틱 노드',
  [UpgradeType.Chitinous_Plating]: '카이트너스 플레이팅',
  [UpgradeType.Anabolic_Synthesis]: '아나볼릭 신테시스',
  
  // Protoss Upgrades
  [UpgradeType.Protoss_Ground_Armor]: '지상 방어력',
  [UpgradeType.Protoss_Air_Armor]: '공중 방어력',
  [UpgradeType.Protoss_Ground_Weapons]: '지상 공격력',
  [UpgradeType.Protoss_Air_Weapons]: '공중 공격력',
  [UpgradeType.Protoss_Plasma_Shields]: '플라스마 쉴드',
  [UpgradeType.Singularity_Charge]: '싱귤라리티 차지',
  [UpgradeType.Leg_Enhancements]: '레그 인핸스먼트',
  [UpgradeType.Scarab_Damage]: '스캐럽 공격력',
  [UpgradeType.Reaver_Capacity]: '리버 수용력',
  [UpgradeType.Gravitic_Drive]: '그래비틱 드라이브',
  [UpgradeType.Sensor_Array]: '센서 어레이',
  [UpgradeType.Gravitic_Boosters]: '그래비틱 부스터',
  [UpgradeType.Khaydarin_Amulet]: '케이다린 아뮬렛',
  [UpgradeType.Apial_Sensors]: '에이피얼 센서',
  [UpgradeType.Gravitic_Thrusters]: '그래비틱 스러스터',
  [UpgradeType.Carrier_Capacity]: '캐리어 수용력',
  [UpgradeType.Khaydarin_Core]: '케이다린 코어',
  [UpgradeType.Argus_Jewel]: '아르거스 쥬얼',
  [UpgradeType.Argus_Talisman]: '아르거스 탈리스만',
  
  // Special
  [UpgradeType.None]: '없음',
  [UpgradeType.Unknown]: '알 수 없음'
} as const;